---
- name: Provision kubemasters.
  hosts: kubemasters
  become: true
  gather_facts: false

  tasks:
    - name: Include tasks to setup hosts.
      ansible.builtin.include_tasks: tasks/setup_hosts.yml
