---
kubernetes_kubeadm_kubelet_config_file_path: '/etc/kubernetes/kubeadm-kubelet-config.yaml'
kubernetes_kubeadm_init_extra_opts: ""

kubernetes_apiserver_advertise_address: "{{ ansible_host }}"

kubernetes_version: "1.28"
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'

kubernetes_pod_network:
  # Flannel CNI.
  cni: 'weave'
  cidr: '10.244.0.0/16'

kubernetes_config_init_configuration:
  localAPIEndpoint:
    advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"

kubernetes_config_cluster_configuration:
  networking:
    podSubnet: "{{ kubernetes_pod_network.cidr }}"
  kubernetesVersion: "{{ kubernetes_version_kubeadm }}"

kubernetes_join_command_extra_opts: ""
