---
- name: Create a cluster on control nodes.
  hosts: all
  become: true

  tasks:
    - name: Include variables.
      ansible.builtin.include_vars: vars/main.yml

    - name: Include control-plane tasks.
      ansible.builtin.include_tasks: tasks/control-plane-setup.yml
      when: "'kubemasters' in group_names"

    - name: Get the kubeadm join command from the Kubernetes control plane.
      ansible.builtin.command: kubeadm token create --print-join-command
      changed_when: false
      register: kubernetes_join_command_result
      when: "'kubemasters' in group_names"

    - name: Set the kubeadm join command globally.
      ansible.builtin.set_fact:
        kubernetes_join_command: >
          {{ kubernetes_join_command_result.stdout }}
          {{ kubernetes_join_command_extra_opts }}
      when: kubernetes_join_command_result.stdout is defined
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['kubenodes'] }}"

    - name: Include nodes setup tasks.
      ansible.builtin.include_tasks: tasks/node-setup.yml
      when: "'kubenodes' in group_names"
