---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
    state: present

- name: Ensure Docker apt repository is enabled.
  block:
    - name: Ensure keyring directory exists.
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Download the key.
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker-apt-keyring.asc
        mode: "0644"
        owner: root
        group: root

    - name: Add Docker repo.
      ansible.builtin.apt_repository:
        repo: >
          deb [arch="amd64" signed-by=/etc/apt/keyrings/docker-apt-keyring.asc]
          https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable
        filename: docker
        state: present

- name: Ensure containerd.io is installed.
  ansible.builtin.apt:
    update_cache: true
    name: containerd.io
    state: present

- name: Ensure containerd service is started and enabled.
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true

- name: Ensure containerd config directory exists.
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"
  register: containerd_dir

- name: Get defaults from containerd.
  ansible.builtin.command:
    cmd: containerd config default
  changed_when: false
  register: containerd_config_default

- name: Prepare containerd/config.toml from default config
  ansible.builtin.copy:
    dest: /tmp/containerd_config.toml
    content: "{{ containerd_config_default.stdout }}"
    mode: "0755"
  changed_when: false

- name: Set Cgroup driver to systemd
  ansible.builtin.lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: '            SystemdCgroup = true'
    state: present
    path: /tmp/containerd_config.toml
  changed_when: false

- name: Make sure SystemdCgroup = false is not set
  ansible.builtin.lineinfile:
    path: /tmp/containerd_config.toml
    state: absent
    line: '            SystemdCgroup = false'
  changed_when: false

- name: Copy config.toml to /etc/containerd
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"

- name: Cleanup temporary file
  ansible.builtin.file:
    path: /tmp/containerd_config.toml
    state: absent
  changed_when: false

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
