---
- name: Create the directory for the kubernetes_config_file
  ansible.builtin.file:
    path: "{{ kubernetes_kubeadm_kubelet_config_file_path | dirname }}"
    state: directory
    mode: "0755"

- name: Deploy the config-file for kubeadm and kubelet
  ansible.builtin.template:
    src: "kubeadm-kubelet-config.j2"
    dest: "{{ kubernetes_kubeadm_kubelet_config_file_path }}"
    mode: "0644"

- name: Check if Kubernetes has already been initialized.
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Initialize Kubernetes control plane with kubeadm init
  ansible.builtin.command: >
    kubeadm init
    --config {{ kubernetes_kubeadm_kubelet_config_file_path }}
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  changed_when: true
  when: not kubernetes_init_stat.stat.exists

- name: Print the init output to screen.
  ansible.builtin.debug:
    var: kubeadmin_init.stdout
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists.
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"

- name: Symlink the kubectl admin.conf to ~/.kube/config.
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: "0644"
